

let pageJSON =
//Form Initialization Values
{
    "BackgroundColor": "#FFFFFFFF",
    "FormTemplateId": "e3cdcdc0-77ec-ea11-a9e9-c9eea06f246e",
    "FormTemplateChId": "1de3c5c0-77ec-ea11-a9ba-af945aba1b5a",
    "CustomerCategoryId": "00000000-0000-0000-0000-000000000000",
    "Version": "4",
    "FormWidth": "800",
    "FormHeight": "1000",
    "MaximumAttachment": "0",
    "AttachmentRequired": "false",
    "UseWorkflowTaskSecurity": "false",
    "AllowOwner": "true",
    "AllowEditor": "true",
    "AllowViewer": "true",
    "ConfirmationPage": null,
    "AttachmentsFolder": "/Attachments",
    "AttachmentsFolderID": "00000000-0000-0000-0000-000000000000",
    "OutsideFormValidationEnabled": "false",
    "OutsideProcessID": "00000000-0000-0000-0000-000000000000",
    "FormPages": [
        {
            //Page values
            "FormPage": [
                {
                    "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                    "PageNumber": "1",
                    "PageName": "Page 1",
                    "FactoryPageName": "Page 1",
                    "Version": "0",
                    "Width": "1100",
                    "Height": "370",
                    "BackgroundColor": "#FFFFFFFF",
                    "FormCanvasWidth": "0",
                    "FormCanvasHeight": "0",
                    "ScaleFactor": "1",
                    "FieldList": [
                        {
                            //Page Header
                            //xsi:type="FieldContainer"
                            "BaseField": {
                                "BackgroundColor": "0",
                                "BackgroundColorString": "#00FFFFFF",
                                "ConnectionString": null,
                                "Container": "0",
                                "ContainerId": "00000000-0000-0000-0000-000000000000",
                                "ContainerLayoutTopOffset": "0",
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": "00000000-0000-0000-0000-000000000000",
                                "ExtCqID": "00000000-0000-0000-0000-000000000000",
                                "ExtEnableQuery": "false",
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                //Field Type
                                "FieldType": "Container",
                                "ForeColor": "0",
                                "ForegroundColorString": "#FF000000",
                                //Element? GUID
                                "ID": "5191d08e-3442-9768-4650-0122fc12930c",
                                "IsRetired": "false",
                                "LayoutLeft": "0",
                                "LayoutTop": "0",
                                //Container Name
                                "Name": "CON_65D_30_004_4__b_hd",
                                //Page GUID
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": "false",
                                "RenderValidationError": "false",
                                "RowID": null,
                                "Section508Compliant": "false",
                                "SectionID": null,
                                "SectionIndex": "0",
                                "TabOrder": "0",
                                "UseColor": "false",
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": "1",
                                "ZOrder": "1",
                                "IsDataReportingColumn": "true",
                                "IsPrintableField": "true",
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                "Index": "0",
                                //Width
                                "Width": "1100",
                                //Height
                                "Height": "140",
                                "FieldList": null,
                                "FieldIdList": null,
                                "Style": "0",
                                "ResponsiveFlow": "0",
                                "isCollapsible": "false"
                            },
                            //Page Header label
                            //xsi:type="FieldLabel"
                            "BaseFieldLabel1": {
                                "BackgroundColor": "0",
                                "BackgroundColorString": "#00FFFFFF",
                                "ConnectionString": null,
                                "Container": "0",
                                //Container GUID
                                "ContainerId": "5191d08e-3442-9768-4650-0122fc12930c",
                                "ContainerLayoutTopOffset": "0",
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": "00000000-0000-0000-0000-000000000000",
                                "ExtCqID": "00000000-0000-0000-0000-000000000000",
                                "ExtEnableQuery": "false",
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                //Field Type
                                "FieldType": "Label",
                                "ForeColor": "0",
                                "ForegroundColorString": "#FF000000",
                                //Element GUID
                                "ID": "e452e716-d8b3-4ad4-5b9f-4b81616ce261",
                                "IsRetired": "false",
                                "LayoutLeft": "10",
                                "LayoutTop": "70",
                                //Field Name
                                "Name": "STAT_65D_30_004_4__b_hd",
                                //Page GUID
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": "false",
                                "RenderValidationError": "false",
                                "RowID": null,
                                "Section508Compliant": "false",
                                "SectionID": null,
                                "SectionIndex": "0",
                                "TabOrder": "0",
                                "UseColor": "false",
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": "1",
                                //Z Order
                                "ZOrder": "5",
                                "IsDataReportingColumn": "true",
                                "IsPrintableField": "true",
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                "Align": "Left",
                                "AssociatedControlID": "00000000-0000-0000-0000-000000000000",
                                //Font Weight - Header Bold
                                "Bold": "true",
                                "EnableQListener": "false",
                                "FontSize": "9",
                                "LabelWrap": "false",
                                //Label Text
                                "Text": "Page Header",
                                //Header Field Width
                                "Width": "600"
                            },
                            //Blue Divider
                            //xsi:type="FieldRectangle"
                            "BaseField": {
                                "BackgroundColor": 0,
                                //Background Color
                                "BackgroundColorString": "#ff3b80cf",
                                "ConnectionString": null,
                                "Container": 0,
                                //Container GUID
                                "ContainerId": "f52e6f88-0a9a-0d7a-6974-1bc2bef198e9",
                                "ContainerLayoutTopOffset": 0,
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": "00000000-0000-0000-0000-000000000000",
                                "ExtCqID": "00000000-0000-0000-0000-000000000000",
                                "ExtEnableQuery": false,
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                "FieldType": "Rectangle",
                                "ForeColor": 0,
                                "ForegroundColorString": "#FF000000",
                                //GUID
                                "ID": "bb319d74-087f-f03e-3d29-2328ba34d20b",
                                "IsRetired": false,
                                //Layout Left
                                "LayoutLeft": 10,
                                //Layout Top
                                "LayoutTop": 80,
                                //Field Name
                                "Name": "Rectangle17",
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": false,
                                "RenderValidationError": false,
                                "RowID": null,
                                "Section508Compliant": false,
                                "SectionID": null,
                                "SectionIndex": 0,
                                "TabOrder": 0,
                                "UseColor": false,
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": 1,
                                "ZOrder": 1,
                                "IsDataReportingColumn": true,
                                "IsPrintableField": true,
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                //Width
                                "Width": 1080,
                                //height
                                "Height": 9,
                                "BorderColorString": "#00ffffff",
                                "BorderThickness": 0,
                                "WidthUsePercent": false,
                                "HeightUsePercent": false
                            },
                            //Grey Header Background
                            //xsi:type="FieldRectangle"
                            "BaseField": {
                                "BackgroundColor": 0,
                                "BackgroundColorString": "#ff9298a0",
                                "ConnectionString": null,
                                "Container": 0,
                                //Container ID
                                "ContainerId": "f52e6f88-0a9a-0d7a-6974-1bc2bef198e9",
                                "ContainerLayoutTopOffset": 0,
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": "00000000-0000-0000-0000-000000000000",
                                "ExtCqID": "00000000-0000-0000-0000-000000000000",
                                "ExtEnableQuery": false,
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                "FieldType": "Rectangle",
                                "ForeColor": 0,
                                "ForegroundColorString": "#FF000000",
                                //GUID
                                "ID": "bb319d74-087f-f03e-3d29-2328ba34d20b",
                                "IsRetired": false,
                                "LayoutLeft": 10,
                                //Layout Top
                                "LayoutTop": 90,
                                "Name": "Rectangle17",
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": false,
                                "RenderValidationError": false,
                                "RowID": null,
                                "Section508Compliant": false,
                                "SectionID": null,
                                "SectionIndex": 0,
                                "TabOrder": 0,
                                "UseColor": false,
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": 1,
                                "ZOrder": 2,
                                "IsDataReportingColumn": true,
                                "IsPrintableField": true,
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                "Width": 1080,
                                "Height": 50,
                                "BorderColorString": "#00ffffff",
                                "BorderThickness": 0,
                                "WidthUsePercent": false,
                                "HeightUsePercent": false
                            },
                            //Section Header
                            //xsi:type="FieldLabel"
                            "BaseFieldLabel2": {
                                "BackgroundColor": "0",
                                //Background Color
                                "BackgroundColorString": "#00FFFFFF",
                                "ConnectionString": null,
                                "Container": "0",
                                //Container GUID
                                "ContainerId": "5191d08e-3442-9768-4650-0122fc12930c",
                                "ContainerLayoutTopOffset": "0",
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": "00000000-0000-0000-0000-000000000000",
                                "ExtCqID": "00000000-0000-0000-0000-000000000000",
                                "ExtEnableQuery": "false",
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                "FieldType": "Label",
                                "ForeColor": "0",
                                "ForegroundColorString": "#FF000000",
                                //GUID
                                "ID": "a9cea8c0-86f8-2942-493a-d4e5e14ce15c",
                                "IsRetired": "false",
                                "LayoutLeft": "30",
                                //Layout Top
                                "LayoutTop": "90",
                                //Header label name
                                "Name": "Label16",
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": "false",
                                "RenderValidationError": "false",
                                "RowID": null,
                                "Section508Compliant": "false",
                                "SectionID": null,
                                "SectionIndex": "0",
                                "TabOrder": "0",
                                "UseColor": "false",
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": "1",
                                "ZOrder": "6",
                                "IsDataReportingColumn": "true",
                                "IsPrintableField": "true",
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                "Align": "Left",
                                "AssociatedControlID": "00000000-0000-0000-0000-000000000000",
                                "Bold": "true",
                                "EnableQListener": "false",
                                //Font Size
                                "FontSize": "12",
                                "LabelWrap": "false",
                                //Section Header Text
                                "Text": "Section Header",
                                //Width
                                "Width": "160"
                            },
                            //End of Header Container Section


                            //Column Header Container Section
                            //xsi:type="FieldContainer"
                            "BaseField": {
                                "BackgroundColor": "0",
                                "BackgroundColorString": "#00FFFFFF",
                                "ConnectionString": null,
                                "Container": "0",
                                //Container GUID
                                "ContainerId": "00000000-0000-0000-0000-000000000000",
                                "ContainerLayoutTopOffset": "0",
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": "00000000-0000-0000-0000-000000000000",
                                "ExtCqID": "00000000-0000-0000-0000-000000000000",
                                "ExtEnableQuery": "false",
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                //Field Type
                                "QueryColumnOperatorMappingList": null,
                                "FieldType": "Container",
                                "ForeColor": "0",
                                "ForegroundColorString": "#FF000000",
                                //Element? GUID
                                "ID": "5191d08e-3442-9768-4650-0122fc12930c",
                                "IsRetired": "false",
                                "LayoutLeft": "0",
                                "LayoutTop": "140",
                                //Container Name
                                "Name": "Column Header Container",
                                //Page GUID
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": "false",
                                "RenderValidationError": "false",
                                "RowID": null,
                                "Section508Compliant": "false",
                                "SectionID": null,
                                "SectionIndex": "0",
                                "TabOrder": "0",
                                "UseColor": "false",
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": "1",
                                "ZOrder": "1",
                                "IsDataReportingColumn": "true",
                                "IsPrintableField": "true",
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                "Index": "0",
                                //Width
                                "Width": "1100",
                                //Height
                                "Height": "50",
                                "FieldList": null,
                                "FieldIdList": null,
                                "Style": "0",
                                "ResponsiveFlow": "0",
                                "isCollapsible": "false"
                            },
                            //Statute Column Header Label
                            //xsi:type="FieldLabel"
                            "BaseFieldLabel3": {
                                "BackgroundColor": "0",
                                //Background Color
                                "BackgroundColorString": "#00FFFFFF",
                                "ConnectionString": null,
                                "Container": "0",
                                //Container GUID
                                "ContainerId": "5191d08e-3442-9768-4650-0122fc12930c",
                                "ContainerLayoutTopOffset": "0",
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": "00000000-0000-0000-0000-000000000000",
                                "ExtCqID": "00000000-0000-0000-0000-000000000000",
                                "ExtEnableQuery": "false",
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                //Field Type
                                "FieldType": "Label",
                                "ForeColor": "0",
                                "ForegroundColorString": "#FF000000",
                                //Field GUID
                                "ID": "d3720a41-7a43-c136-f240-d57dce3269aa",
                                "IsRetired": "false",
                                //Layout Left
                                "LayoutLeft": "10",
                                //Layout Top
                                "LayoutTop": "150",
                                //Field Name
                                "Name": "Label17",
                                //Page GUID
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": "false",
                                "RenderValidationError": "false",
                                "RowID": null,
                                "Section508Compliant": "false",
                                "SectionID": null,
                                "SectionIndex": "0",
                                "TabOrder": "0",
                                "UseColor": "false",
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": "1",
                                "ZOrder": "2",
                                "IsDataReportingColumn": "true",
                                "IsPrintableField": "true",
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                "Align": "Left",
                                "AssociatedControlID": "00000000-0000-0000-0000-000000000000",
                                //Font Weight
                                "Bold": "true",
                                "EnableQListener": "false",
                                //Font Size
                                "FontSize": "9",
                                "LabelWrap": "false",
                                //Label Text
                                "Text": "Statute",
                                //Width
                                "Width": "72"
                            },
                            //Citation Column Header Label
                            //xsi:type="FieldLabel"
                            "BaseFieldLabel3": {
                                "BackgroundColor": "0",
                                "BackgroundColorString": "#00FFFFFF",
                                "ConnectionString": null,
                                "Container": "0",
                                //Container GUID
                                "ContainerId": "5191d08e-3442-9768-4650-0122fc12930c",
                                "ContainerLayoutTopOffset": "0",
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": "00000000-0000-0000-0000-000000000000",
                                "ExtCqID": "00000000-0000-0000-0000-000000000000",
                                "ExtEnableQuery": "false",
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                //Field Type
                                "FieldType": "Label",
                                "ForeColor": "0",
                                "ForegroundColorString": "#FF000000",
                                //Field GUID
                                "ID": "d3720a41-7a43-c136-f240-d57dce3269aa",
                                "IsRetired": "false",
                                //Layout Left
                                "LayoutLeft": "550",
                                //Layout Top
                                "LayoutTop": "150",
                                //Field Name
                                "Name": "Label17",
                                //Page GUID
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": "false",
                                "RenderValidationError": "false",
                                "RowID": null,
                                "Section508Compliant": "false",
                                "SectionID": null,
                                "SectionIndex": "0",
                                "TabOrder": "0",
                                "UseColor": "false",
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": "1",
                                "ZOrder": "2",
                                "IsDataReportingColumn": "true",
                                "IsPrintableField": "true",
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                "Align": "Left",
                                "AssociatedControlID": "00000000-0000-0000-0000-000000000000",
                                //Font Weight
                                "Bold": "true",
                                "EnableQListener": "false",
                                //Font Size
                                "FontSize": "9",
                                "LabelWrap": "false",
                                //Label Text
                                "Text": "Citations",
                                //Width
                                "Width": "72"
                            },
                            //Comments Column Header Label
                            //xsi:type="FieldLabel"
                            "BaseFieldLabel3": {
                                "BackgroundColor": "0",
                                "BackgroundColorString": "#00FFFFFF",
                                "ConnectionString": null,
                                "Container": "0",
                                //Container GUID
                                "ContainerId": "5191d08e-3442-9768-4650-0122fc12930c",
                                "ContainerLayoutTopOffset": "0",
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": "00000000-0000-0000-0000-000000000000",
                                "ExtCqID": "00000000-0000-0000-0000-000000000000",
                                "ExtEnableQuery": "false",
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                //Field Type
                                "FieldType": "Label",
                                "ForeColor": "0",
                                "ForegroundColorString": "#FF000000",
                                //Field GUID
                                "ID": "d3720a41-7a43-c136-f240-d57dce3269aa",
                                "IsRetired": "false",
                                //Layout Left
                                "LayoutLeft": "660",
                                //Layout Top
                                "LayoutTop": "150",
                                //Field Name
                                "Name": "Label17",
                                //Page GUID
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": "false",
                                "RenderValidationError": "false",
                                "RowID": null,
                                "Section508Compliant": "false",
                                "SectionID": null,
                                "SectionIndex": "0",
                                "TabOrder": "0",
                                "UseColor": "false",
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": "1",
                                "ZOrder": "2",
                                "IsDataReportingColumn": "true",
                                "IsPrintableField": "true",
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                "Align": "Left",
                                "AssociatedControlID": "00000000-0000-0000-0000-000000000000",
                                //Font Weight
                                "Bold": "true",
                                "EnableQListener": "false",
                                //Font Size
                                "FontSize": "9",
                                "LabelWrap": "false",
                                //Label Text
                                "Text": "Comments",
                                //Width
                                "Width": "72"
                            },
                            //Comments Column Header Label
                            //xsi:type="FieldLabel"
                            "BaseFieldLabel3": {
                                "BackgroundColor": "0",
                                "BackgroundColorString": "#00FFFFFF",
                                "ConnectionString": null,
                                "Container": "0",
                                //Container GUID
                                "ContainerId": "5191d08e-3442-9768-4650-0122fc12930c",
                                "ContainerLayoutTopOffset": "0",
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": "00000000-0000-0000-0000-000000000000",
                                "ExtCqID": "00000000-0000-0000-0000-000000000000",
                                "ExtEnableQuery": "false",
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                //Field Type
                                "FieldType": "Label",
                                "ForeColor": "0",
                                "ForegroundColorString": "#FF000000",
                                //Field GUID
                                "ID": "d3720a41-7a43-c136-f240-d57dce3269aa",
                                "IsRetired": "false",
                                //Layout Left
                                "LayoutLeft": "1000",
                                //Layout Top
                                "LayoutTop": "150",
                                //Field Name
                                "Name": "Label17",
                                //Page GUID
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": "false",
                                "RenderValidationError": "false",
                                "RowID": null,
                                "Section508Compliant": "false",
                                "SectionID": null,
                                "SectionIndex": "0",
                                "TabOrder": "0",
                                "UseColor": "false",
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": "1",
                                "ZOrder": "2",
                                "IsDataReportingColumn": "true",
                                "IsPrintableField": "true",
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                "Align": "Left",
                                "AssociatedControlID": "00000000-0000-0000-0000-000000000000",
                                //Font Weight
                                "Bold": "true",
                                "EnableQListener": "false",
                                //Font Size
                                "FontSize": "9",
                                "LabelWrap": "false",
                                //Label Text
                                "Text": "Violation",
                                //Width
                                "Width": "72"
                            },
                            //Blue Divider Line
                            //xsi:type="FieldRectangle"
                            "BaseField": {
                                "BackgroundColor": 0,
                                //Background Color
                                "BackgroundColorString": "#ff3b80cf",
                                "ConnectionString": null,
                                "Container": 0,
                                //Container ID
                                "ContainerId": "f52e6f88-0a9a-0d7a-6974-1bc2bef198e9",
                                "ContainerLayoutTopOffset": 0,
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": "00000000-0000-0000-0000-000000000000",
                                "ExtCqID": "00000000-0000-0000-0000-000000000000",
                                "ExtEnableQuery": false,
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                //Field Type
                                "FieldType": "Rectangle",
                                "ForeColor": 0,
                                "ForegroundColorString": "#FF000000",
                                //Field GUID
                                "ID": "bb319d74-087f-f03e-3d29-2328ba34d20b",
                                "IsRetired": false,
                                "LayoutLeft": 10,
                                //Layout Top
                                "LayoutTop": 170,
                                //Field Name
                                "Name": "Rectangle17",
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": false,
                                "RenderValidationError": false,
                                "RowID": null,
                                "Section508Compliant": false,
                                "SectionID": null,
                                "SectionIndex": 0,
                                "TabOrder": 0,
                                "UseColor": false,
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": 1,
                                "ZOrder": 2,
                                "IsDataReportingColumn": true,
                                "IsPrintableField": true,
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                //Width
                                "Width": 1080,
                                //Height
                                "Height": 9,
                                "BorderColorString": "#00ffffff",
                                "BorderThickness": 0,
                                "WidthUsePercent": false,
                                "HeightUsePercent": false
                            },
                            //End of Column Header Section

                            //Row Section
                            //Row Container
                            //xsi:type="FieldContainer"
                            "BaseField": {
                                "BackgroundColor": "0",
                                "BackgroundColorString": "#00FFFFFF",
                                "ConnectionString": null,
                                "Container": "0",
                                //Container GUID
                                "ContainerId": "00000000-0000-0000-0000-000000000000",
                                "ContainerLayoutTopOffset": "0",
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": "00000000-0000-0000-0000-000000000000",
                                "ExtCqID": "00000000-0000-0000-0000-000000000000",
                                "ExtEnableQuery": "false",
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                //Field Type
                                "FieldType": "Container",
                                "ForeColor": "0",
                                "ForegroundColorString": "#FF000000",
                                //Element? GUID
                                "ID": "5191d08e-3442-9768-4650-0122fc12930c",
                                "IsRetired": "false",
                                //Layout Left
                                "LayoutLeft": "0",
                                //Layout Top
                                "LayoutTop": "190",
                                //Container Name
                                "Name": "Name of Statute",
                                //Page GUID
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": "false",
                                "RenderValidationError": "false",
                                "RowID": null,
                                "Section508Compliant": "false",
                                "SectionID": null,
                                "SectionIndex": "0",
                                "TabOrder": "0",
                                "UseColor": "false",
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": "1",
                                "ZOrder": "1",
                                "IsDataReportingColumn": "true",
                                "IsPrintableField": "true",
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                "Index": "0",
                                //Width
                                "Width": "1100",
                                //Height
                                "Height": "90",
                                "FieldList": null,
                                "FieldIdList": null,
                                "Style": "0",
                                "ResponsiveFlow": "0",
                                "isCollapsible": "false"
                            },
                            //Statute Label
                            //xsi:type="FieldLabel"
                            "BaseFieldLabel3": {
                                "BackgroundColor": "0",
                                "BackgroundColorString": "#00FFFFFF",
                                "ConnectionString": null,
                                "Container": "0",
                                //Container GUID
                                "ContainerId": "5191d08e-3442-9768-4650-0122fc12930c",
                                "ContainerLayoutTopOffset": "0",
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": "00000000-0000-0000-0000-000000000000",
                                "ExtCqID": "00000000-0000-0000-0000-000000000000",
                                "ExtEnableQuery": "false",
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                //Field Type
                                "FieldType": "Label",
                                "ForeColor": "0",
                                "ForegroundColorString": "#FF000000",
                                //Field GUID
                                "ID": "d3720a41-7a43-c136-f240-d57dce3269aa",
                                "IsRetired": "false",
                                //Layout Left
                                "LayoutLeft": "10",
                                //Layout Top
                                "LayoutTop": "200",
                                //Field Name
                                "Name": "Label17",
                                //Page GUID
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": "false",
                                "RenderValidationError": "false",
                                "RowID": null,
                                "Section508Compliant": "false",
                                "SectionID": null,
                                "SectionIndex": "0",
                                "TabOrder": "0",
                                "UseColor": "false",
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": "1",
                                "ZOrder": "2",
                                "IsDataReportingColumn": "true",
                                "IsPrintableField": "true",
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                "Align": "Left",
                                "AssociatedControlID": "00000000-0000-0000-0000-000000000000",
                                //Font Weight
                                "Bold": "true",
                                "EnableQListener": "false",
                                //Font Size
                                "FontSize": "8",
                                //Text wrap
                                "LabelWrap": "false",
                                //Label Text
                                "Text": "Statute 1A",
                                //Width
                                "Width": "92"
                            },
                            //Citation Description Label ** Key Field
                            //xsi:type="FieldLabel"
                            "BaseFieldLabel3": {
                                "BackgroundColor": "0",
                                "BackgroundColorString": "#00FFFFFF",
                                "ConnectionString": null,
                                "Container": "0",
                                //Container GUID
                                "ContainerId": "5191d08e-3442-9768-4650-0122fc12930c",
                                "ContainerLayoutTopOffset": "0",
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": "00000000-0000-0000-0000-000000000000",
                                "ExtCqID": "00000000-0000-0000-0000-000000000000",
                                "ExtEnableQuery": "false",
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                //Field Type
                                "FieldType": "Label",
                                "ForeColor": "0",
                                "ForegroundColorString": "#FF000000",
                                //Field GUID
                                "ID": "d3720a41-7a43-c136-f240-d57dce3269aa",
                                "IsRetired": "false",
                                //Layout Left
                                "LayoutLeft": "110",
                                //Layout Top
                                "LayoutTop": "200",
                                //Field Name
                                "Name": "Label17",
                                //Page GUID
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": "false",
                                "RenderValidationError": "false",
                                "RowID": null,
                                "Section508Compliant": "false",
                                "SectionID": null,
                                "SectionIndex": "0",
                                "TabOrder": "0",
                                "UseColor": "false",
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": "1",
                                "ZOrder": "2",
                                "IsDataReportingColumn": "true",
                                "IsPrintableField": "true",
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                "Align": "Left",
                                "AssociatedControlID": "00000000-0000-0000-0000-000000000000",
                                //Font Weight
                                "Bold": "false",
                                "EnableQListener": "false",
                                //Font Size
                                "FontSize": "8",
                                //Text wrap - true for Citation Description
                                "LabelWrap": "true",
                                //Label Text
                                "Text": "Citation Description goes here",
                                //Width
                                "Width": "400"
                            },
                            //Result DDL
                            //xsi:type="FieldDropDownList3"
                            "BaseField": {
                                "BackgroundColor": 0,
                                "BackgroundColorString": "#00FFFFFF",
                                "ConnectionString": null,
                                "Container": 0,
                                //Container GUID
                                "ContainerId": "ae9a009f-dff1-9410-e337-9d33cdd90347",
                                "ContainerLayoutTopOffset": 0,
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": 00000000 - 0000 - 0000 - 0000 - 000000000000,
                                "ExtCqID": 00000000 - 0000 - 0000 - 0000 - 000000000000,
                                "ExtEnableQuery": false,
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                "FieldType": "DropDownList",
                                "ForeColor": 0,
                                "ForegroundColorString": "#FF000000",
                                //Field GUID
                                "ID": "e4ba42e2-4f0c-ff2b-49a0-b1c5513af852",
                                "IsRetired": false,
                                //Layout Left
                                "LayoutLeft": 550,
                                //Layout Top
                                "LayoutTop": 200,
                                //Field Name
                                "Name": "Result 1",
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": false,
                                "RenderValidationError": false,
                                "RowID": null,
                                "Section508Compliant": false,
                                "SectionID": null,
                                "SectionIndex": 0,
                                "TabOrder": 0,
                                "UseColor": false,
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": 3,
                                "ZOrder": 1,
                                "IsDataReportingColumn": true,
                                "IsPrintableField": true,
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                "IsValidatorShowing": false,
                                "ValidationType": "NoValidation",
                                "CascadedParentListId": "00000000-0000-0000-0000-000000000000",
                                "CascadedParentListValue": null,
                                "CcID": "00000000-0000-0000-0000-000000000000",
                                "ChildCascadedList": null,
                                "CqID": "00000000-0000-0000-0000-000000000000",
                                "CqTextFieldName": null,
                                "CqValueFieldName": null,
                                "DropDownConnectionType": "CustomQuery",
                                "EnableCascadedList": false,
                                "EnableCustomQuery": false,
                                "EnableFormQuery": false,
                                "EnableQListener": false,
                                "FillCacheEnabled": true,
                                "FillCacheTimeout": 0.5,
                                "FillConnectionString": null,
                                "FillQuery": null,
                                "FormQueryID": null,
                                "HasCascadedParentValue": false,
                                "IsParentCascadeControl": false,
                                //Item List
                                "ItemList": {
                                    "string": "NA",
                                },
                                "OptionList": null,
                                "ReportingProperty": "Text",
                                "ReportingPropertySetting": 0,
                                "WorkflowConditionsDataProperty": Value,
                                "WorkflowConditionsDataPropertySetting": 1,
                                "SelectedIndex": 0,
                                "SelectedText": null,
                                //Width
                                "Width": 80,
                                "CascadeQueryColumnOperatorMappingList": null,
                            },
                            //Comments Text Box
                            //xsi:type="FieldTextArea3"
                            "BaseField": {
                            "BackgroundColor": 0,
                            "BackgroundColorString": "#FFFFFFFF",
                            "ConnectionString": null, 
                            "Container": 0, 
                            //Container GUID
                            "ContainerId": "ae9a009f-dff1-9410-e337-9d33cdd90347",
                            "ContainerLayoutTopOffset": 0,
                            "ErrorMessage": null, 
                            "ErrorPIC": "~\\scripts\\error.gif",
                            "ExtCcID": "00000000-0000-0000-0000-000000000000",
                            "ExtCqID": "00000000-0000-0000-0000-000000000000",
                            "ExtEnableQuery": false,
                            "ExternalQuery": null, 
                            "FieldMappings": null, 
                            "FieldToColumnMappingList": null, 
                            "QueryColumnOperatorMappingList": null, 
                            "FieldType": "MultiLineTextbox", 
                            "ForeColor": 0,
                            "ForegroundColorString": "#FF000000",
                            "ID": "6664542a-4cb0-57d2-928b-2429ebbc0d81", 
                            "IsRetired": false,
                            //Layout Left
                            "LayoutLeft": 660,
                            //Layout Top
                            "LayoutTop": 200,
                            //Field Name
                            "Name": "Comments 1",
                            "PageId": "63751eca-6179-06ff-68bb-296b959bb08c", 
                            "PrimaryKey": null, 
                            "RenderAsReadOnly": false,
                            "RenderValidationError": false,
                            "RowID": null, 
                            "Section508Compliant": false,
                            "SectionID": null, 
                            "SectionIndex": 0,
                            "TabOrder": 0,
                            "UseColor": false, 
                            "ValidationErrorMessage": null, 
                            "ValidationErrorPic": "~\\scripts\\error.gif", 
                            "Value": null, 
                            "Version": 3,
                            "ZOrder": 1,
                            "IsDataReportingColumn": true,
                            "IsPrintableField": true,
                            "FormVersion": "FormVersion4",
                            "AccessibilityLabel": null, 
                            "IsValidatorShowing": false,
                            "ValidationType": "NoValidation",
                            "EnableQListener": false,
                            //Character length
                            "Length": 1000,
                            //Rows
                            "Rows": 4,
                            "Text": null, 
                            //Font size
                            "FontSize": 8, 
                            //Width
                            "Width": 300, 
                            //Height
                            "Height": 6,
                            "RenderAsHtmlEditor": false,
                            },
                            //Violation DDL
                            //xsi:type="FieldDropDownList3"
                            "BaseField": {
                                "BackgroundColor": 0,
                                "BackgroundColorString": "#00FFFFFF",
                                "ConnectionString": null,
                                "Container": 0,
                                //Container GUID
                                "ContainerId": "ae9a009f-dff1-9410-e337-9d33cdd90347",
                                "ContainerLayoutTopOffset": 0,
                                "ErrorMessage": null,
                                "ErrorPIC": "~\\scripts\\error.gif",
                                "ExtCcID": 00000000 - 0000 - 0000 - 0000 - 000000000000,
                                "ExtCqID": 00000000 - 0000 - 0000 - 0000 - 000000000000,
                                "ExtEnableQuery": false,
                                "ExternalQuery": null,
                                "FieldMappings": null,
                                "FieldToColumnMappingList": null,
                                "QueryColumnOperatorMappingList": null,
                                //Field Type
                                "FieldType": "DropDownList",
                                "ForeColor": 0,
                                "ForegroundColorString": "#FF000000",
                                //Field GUID
                                "ID": "e4ba42e2-4f0c-ff2b-49a0-b1c5513af852",
                                "IsRetired": false,
                                //Layout Left
                                "LayoutLeft": 1000,
                                //Layout Top
                                "LayoutTop": 200,
                                //Field Name
                                "Name": "ViolationDDL",
                                "PageId": "63751eca-6179-06ff-68bb-296b959bb08c",
                                "PrimaryKey": null,
                                "RenderAsReadOnly": false,
                                "RenderValidationError": false,
                                "RowID": null,
                                "Section508Compliant": false,
                                "SectionID": null,
                                "SectionIndex": 0,
                                "TabOrder": 0,
                                "UseColor": false,
                                "ValidationErrorMessage": null,
                                "ValidationErrorPic": "~\\scripts\\error.gif",
                                "Value": null,
                                "Version": 3,
                                "ZOrder": 1,
                                "IsDataReportingColumn": true,
                                "IsPrintableField": true,
                                "FormVersion": "FormVersion4",
                                "AccessibilityLabel": null,
                                "IsValidatorShowing": false,
                                "ValidationType": "NoValidation",
                                "CascadedParentListId": "00000000-0000-0000-0000-000000000000",
                                "CascadedParentListValue": null,
                                "CcID": "00000000-0000-0000-0000-000000000000",
                                "ChildCascadedList": null,
                                "CqID": "00000000-0000-0000-0000-000000000000",
                                "CqTextFieldName": null,
                                "CqValueFieldName": null,
                                "DropDownConnectionType": "CustomQuery",
                                "EnableCascadedList": false,
                                "EnableCustomQuery": false,
                                "EnableFormQuery": false,
                                "EnableQListener": false,
                                "FillCacheEnabled": true,
                                "FillCacheTimeout": 0.5,
                                "FillConnectionString": null,
                                "FillQuery": null,
                                "FormQueryID": null,
                                "HasCascadedParentValue": false,
                                "IsParentCascadeControl": false,
                                //Item List
                                "ItemList": {
                                    "string": "NA",
                                },
                                "OptionList": null,
                                "ReportingProperty": "Text",
                                "ReportingPropertySetting": 0,
                                "WorkflowConditionsDataProperty": Value,
                                "WorkflowConditionsDataPropertySetting": 1,
                                "SelectedIndex": 0,
                                "SelectedText": null,
                                //Width
                                "Width": 80,
                                "CascadeQueryColumnOperatorMappingList": null,
                            },
                        },
                        
                    ],
                    "IsRetired": false,
                }
            ]
        },
    ],
    //Closing Page Elements
    "GroupsHolder": {
		"FormTemplateID": "a38a0f70-7aec-ea11-a9ba-af945aba1b5a",
		"GroupCollection": null,
		"HasBuiltinGroups": false
        },
	"TextboxFontSize": 10,
	"PrintAreaWidthOption": 0, 
	"PrintAreaWidth": 1024, 
	"PdfPaperSize": 1, 
	"PdfPaperSizeWidth": 0,
	"PdfPaperSizeHeight": 0,
	"PdfTopMargin": 0, 
	"PdfRightMargin": 0, 
	"PdfBottomMargin": 0, 
	"PdfLeftMargin": 0, 
	"PdfPageOrientation": "Portrait",
	"AssimilateLatestFormTemplate": true,
	"FieldListSaveKey": "00000000-0000-0000-0000-000000000000",
	"UpdateDocumentRelationshipDocId": false,
	"FormTemplateType": "FormTemplate",
	"InheritedFormTemplateType": "FormTemplate", 
	"InheritedFormTemplateId": "00000000-0000-0000-0000-000000000000",
	"InheritedFormTemplateRevisionId": "00000000-0000-0000-0000-000000000000", 
	"SaveDateTime": "2020-09-30T19:03:48Z",
	"ScriptLibrary": null,
	"ScriptAssignments": null,
	"ImageControlImages": null,
	"Groups": null,
	"AllPagesRenderAsOne": false,
}